export const TEAM_DETAILS = 'TEAM_DETAILS';
export const PLAYER_DETAILS = 'TEAM_DETAILS';
export const SET_TEAM_DETAILS_LOADING = 'SET_TEAM_DETAILS_LOADING';
export const SET_PLAYER_DETAILS_LOADING = 'SET_PLAYER_DETAILS_LOADING';
export const SET_MATCH_DETAILS_LOADING = 'SET_MATCH_DETAILS_LOADING';
export const MATCH_DETAILS = 'MATCH_DETAILS';
